setOnActuator(player(brain(player(move(X))))):-
%greenCar(green(car(moveRight(X)))).
%greenCar(green(car(xpos(X)))).
%greenCar(green(car(ypos(X)))).
%greenCar2(green2(car(moveRight(X)))).
%greenCar2(green2(car(xpos(X)))).
%greenCar2(green2(car(ypos(X)))).
%greenCar3(green3(car(moveRight(X)))).
%greenCar3(green3(car(xpos(X)))).
%greenCar3(green3(car(ypos(X)))).
%greenCar4(green4(car(moveRight(X)))).
%greenCar4(green4(car(xpos(X)))).
%greenCar4(green4(car(ypos(X)))).
%orangeCar(orange(car(moveRight(X)))).
%orangeCar(orange(car(xpos(X)))).
%orangeCar(orange(car(ypos(X)))).
%orangeCar2(orange2(car(moveRight(X)))).
%orangeCar2(orange2(car(xpos(X)))).
%orangeCar2(orange2(car(ypos(X)))).
%pinkCar(pink(car(moveRight(X)))).
%pinkCar(pink(car(xpos(X)))).
%pinkCar(pink(car(ypos(X)))).
%pinkCar2(pink2(car(moveRight(X)))).
%pinkCar2(pink2(car(xpos(X)))).
%pinkCar2(pink2(car(ypos(X)))).
%purpleCar(purple(car(moveRight(X)))).
%purpleCar(purple(car(xpos(X)))).
%purpleCar(purple(car(ypos(X)))).
%purpleCar2(purple2(car(moveRight(X)))).
%purpleCar2(purple2(car(xpos(X)))).
%purpleCar2(purple2(car(ypos(X)))).
%whiteCar(white(car(moveRight(X)))).
%whiteCar(white(car(xpos(X)))).
%whiteCar(white(car(ypos(X)))).
%whiteCar2(white2(car(moveRight(X)))).
%whiteCar2(white2(car(xpos(X)))).
%whiteCar2(white2(car(ypos(X)))).
%playerSensor(brain(player(xpos(X)))).
%playerSensor(brain(player(ypos(X)))).
