//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/francesco/Scrivania/EmbASP-antlr-grammars/dlv2/DLV2Parser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDLV2ParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class DLV2ParserBaseListener : IDLV2ParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DLV2Parser.answer_set"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnswer_set([NotNull] DLV2Parser.Answer_setContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DLV2Parser.answer_set"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnswer_set([NotNull] DLV2Parser.Answer_setContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DLV2Parser.cost"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCost([NotNull] DLV2Parser.CostContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DLV2Parser.cost"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCost([NotNull] DLV2Parser.CostContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DLV2Parser.level"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLevel([NotNull] DLV2Parser.LevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DLV2Parser.level"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLevel([NotNull] DLV2Parser.LevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DLV2Parser.model"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModel([NotNull] DLV2Parser.ModelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DLV2Parser.model"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModel([NotNull] DLV2Parser.ModelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DLV2Parser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutput([NotNull] DLV2Parser.OutputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DLV2Parser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutput([NotNull] DLV2Parser.OutputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DLV2Parser.predicate_atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate_atom([NotNull] DLV2Parser.Predicate_atomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DLV2Parser.predicate_atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate_atom([NotNull] DLV2Parser.Predicate_atomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DLV2Parser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] DLV2Parser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DLV2Parser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] DLV2Parser.TermContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
