//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from IDLVParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class IDLVParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		IGNORE=1, COMMA=2, INTEGER_CONSTANT=3, ATOM_END=4, IDENTIFIER=5, STRING_CONSTANT=6, 
		TERMS_BEGIN=7, TERMS_END=8;
	public const int
		RULE_output = 0, RULE_minimal_model = 1, RULE_predicate_atom = 2, RULE_term = 3;
	public static readonly string[] ruleNames = {
		"output", "minimal_model", "predicate_atom", "term"
	};

	private static readonly string[] _LiteralNames = {
		null, null, "','", null, "'.'", null, null, "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "IGNORE", "COMMA", "INTEGER_CONSTANT", "ATOM_END", "IDENTIFIER", 
		"STRING_CONSTANT", "TERMS_BEGIN", "TERMS_END"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "IDLVParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static IDLVParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public IDLVParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public IDLVParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class OutputContext : ParserRuleContext {
		public Minimal_modelContext minimal_model() {
			return GetRuleContext<Minimal_modelContext>(0);
		}
		public OutputContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_output; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIDLVParserVisitor<TResult> typedVisitor = visitor as IIDLVParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOutput(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OutputContext output() {
		OutputContext _localctx = new OutputContext(Context, State);
		EnterRule(_localctx, 0, RULE_output);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 8; minimal_model();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Minimal_modelContext : ParserRuleContext {
		public Predicate_atomContext[] predicate_atom() {
			return GetRuleContexts<Predicate_atomContext>();
		}
		public Predicate_atomContext predicate_atom(int i) {
			return GetRuleContext<Predicate_atomContext>(i);
		}
		public ITerminalNode[] ATOM_END() { return GetTokens(IDLVParser.ATOM_END); }
		public ITerminalNode ATOM_END(int i) {
			return GetToken(IDLVParser.ATOM_END, i);
		}
		public Minimal_modelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_minimal_model; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIDLVParserVisitor<TResult> typedVisitor = visitor as IIDLVParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMinimal_model(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Minimal_modelContext minimal_model() {
		Minimal_modelContext _localctx = new Minimal_modelContext(Context, State);
		EnterRule(_localctx, 2, RULE_minimal_model);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 15;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==IDENTIFIER) {
				{
				{
				State = 10; predicate_atom();
				State = 11; Match(ATOM_END);
				}
				}
				State = 17;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Predicate_atomContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(IDLVParser.IDENTIFIER, 0); }
		public ITerminalNode TERMS_BEGIN() { return GetToken(IDLVParser.TERMS_BEGIN, 0); }
		public TermContext[] term() {
			return GetRuleContexts<TermContext>();
		}
		public TermContext term(int i) {
			return GetRuleContext<TermContext>(i);
		}
		public ITerminalNode TERMS_END() { return GetToken(IDLVParser.TERMS_END, 0); }
		public ITerminalNode[] COMMA() { return GetTokens(IDLVParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(IDLVParser.COMMA, i);
		}
		public Predicate_atomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_predicate_atom; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIDLVParserVisitor<TResult> typedVisitor = visitor as IIDLVParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPredicate_atom(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Predicate_atomContext predicate_atom() {
		Predicate_atomContext _localctx = new Predicate_atomContext(Context, State);
		EnterRule(_localctx, 4, RULE_predicate_atom);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 18; Match(IDENTIFIER);
			State = 30;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==TERMS_BEGIN) {
				{
				State = 19; Match(TERMS_BEGIN);
				State = 20; term();
				State = 25;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 21; Match(COMMA);
					State = 22; term();
					}
					}
					State = 27;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 28; Match(TERMS_END);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TermContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(IDLVParser.IDENTIFIER, 0); }
		public ITerminalNode INTEGER_CONSTANT() { return GetToken(IDLVParser.INTEGER_CONSTANT, 0); }
		public ITerminalNode STRING_CONSTANT() { return GetToken(IDLVParser.STRING_CONSTANT, 0); }
		public TermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_term; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IIDLVParserVisitor<TResult> typedVisitor = visitor as IIDLVParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TermContext term() {
		TermContext _localctx = new TermContext(Context, State);
		EnterRule(_localctx, 6, RULE_term);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 32;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INTEGER_CONSTANT) | (1L << IDENTIFIER) | (1L << STRING_CONSTANT))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\n', '%', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', '\t', 
		'\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '\x10', 
		'\n', '\x3', '\f', '\x3', '\xE', '\x3', '\x13', '\v', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', '\x1A', 
		'\n', '\x4', '\f', '\x4', '\xE', '\x4', '\x1D', '\v', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x5', '\x4', '!', '\n', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x2', '\x2', '\x6', '\x2', '\x4', '\x6', '\b', '\x2', '\x3', 
		'\x4', '\x2', '\x5', '\x5', '\a', '\b', '\x2', '#', '\x2', '\n', '\x3', 
		'\x2', '\x2', '\x2', '\x4', '\x11', '\x3', '\x2', '\x2', '\x2', '\x6', 
		'\x14', '\x3', '\x2', '\x2', '\x2', '\b', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\n', '\v', '\x5', '\x4', '\x3', '\x2', '\v', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\f', '\r', '\x5', '\x6', '\x4', '\x2', '\r', '\xE', '\a', '\x6', 
		'\x2', '\x2', '\xE', '\x10', '\x3', '\x2', '\x2', '\x2', '\xF', '\f', 
		'\x3', '\x2', '\x2', '\x2', '\x10', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\xF', '\x3', '\x2', '\x2', '\x2', '\x11', '\x12', '\x3', '\x2', 
		'\x2', '\x2', '\x12', '\x5', '\x3', '\x2', '\x2', '\x2', '\x13', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x14', ' ', '\a', '\a', '\x2', '\x2', '\x15', 
		'\x16', '\a', '\t', '\x2', '\x2', '\x16', '\x1B', '\x5', '\b', '\x5', 
		'\x2', '\x17', '\x18', '\a', '\x4', '\x2', '\x2', '\x18', '\x1A', '\x5', 
		'\b', '\x5', '\x2', '\x19', '\x17', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x1E', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x1E', 
		'\x1F', '\a', '\n', '\x2', '\x2', '\x1F', '!', '\x3', '\x2', '\x2', '\x2', 
		' ', '\x15', '\x3', '\x2', '\x2', '\x2', ' ', '!', '\x3', '\x2', '\x2', 
		'\x2', '!', '\a', '\x3', '\x2', '\x2', '\x2', '\"', '#', '\t', '\x2', 
		'\x2', '\x2', '#', '\t', '\x3', '\x2', '\x2', '\x2', '\x5', '\x11', '\x1B', 
		' ',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
