//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\DatalogGrammar.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class DatalogGrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, IDENTIFIER=4, INTEGER=5, STRING=6, WHITESPACE=7;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "IDENTIFIER", "INTEGER", "STRING", "WHITESPACE"
	};


	public DatalogGrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public DatalogGrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "','", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, "IDENTIFIER", "INTEGER", "STRING", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "DatalogGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static DatalogGrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\t', '\x35', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', '\x1A', 
		'\n', '\x5', '\f', '\x5', '\xE', '\x5', '\x1D', '\v', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\a', '\x6', '\"', '\n', '\x6', '\f', '\x6', 
		'\xE', '\x6', '%', '\v', '\x6', '\x5', '\x6', '\'', '\n', '\x6', '\x3', 
		'\a', '\x3', '\a', '\a', '\a', '+', '\n', '\a', '\f', '\a', '\xE', '\a', 
		'.', '\v', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x2', '\x2', '\t', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x3', '\x2', 
		'\b', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x6', '\x2', '\x32', ';', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\x3', '\x2', '\x33', ';', 
		'\x3', '\x2', '\x32', ';', '\x3', '\x2', '$', '$', '\x5', '\x2', '\v', 
		'\f', '\xF', '\xF', '\"', '\"', '\x2', '\x38', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x3', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x5', '\x13', '\x3', '\x2', '\x2', '\x2', '\a', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\t', '\x17', '\x3', '\x2', '\x2', '\x2', '\v', '&', 
		'\x3', '\x2', '\x2', '\x2', '\r', '(', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x11', '\x12', '\a', '*', '\x2', 
		'\x2', '\x12', '\x4', '\x3', '\x2', '\x2', '\x2', '\x13', '\x14', '\a', 
		'.', '\x2', '\x2', '\x14', '\x6', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'\x16', '\a', '+', '\x2', '\x2', '\x16', '\b', '\x3', '\x2', '\x2', '\x2', 
		'\x17', '\x1B', '\t', '\x2', '\x2', '\x2', '\x18', '\x1A', '\t', '\x3', 
		'\x2', '\x2', '\x19', '\x18', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x1B', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1C', '\n', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x1E', '\'', 
		'\a', '\x32', '\x2', '\x2', '\x1F', '#', '\t', '\x4', '\x2', '\x2', ' ', 
		'\"', '\t', '\x5', '\x2', '\x2', '!', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\"', '%', '\x3', '\x2', '\x2', '\x2', '#', '!', '\x3', '\x2', '\x2', 
		'\x2', '#', '$', '\x3', '\x2', '\x2', '\x2', '$', '\'', '\x3', '\x2', 
		'\x2', '\x2', '%', '#', '\x3', '\x2', '\x2', '\x2', '&', '\x1E', '\x3', 
		'\x2', '\x2', '\x2', '&', '\x1F', '\x3', '\x2', '\x2', '\x2', '\'', '\f', 
		'\x3', '\x2', '\x2', '\x2', '(', ',', '\a', '$', '\x2', '\x2', ')', '+', 
		'\n', '\x6', '\x2', '\x2', '*', ')', '\x3', '\x2', '\x2', '\x2', '+', 
		'.', '\x3', '\x2', '\x2', '\x2', ',', '*', '\x3', '\x2', '\x2', '\x2', 
		',', '-', '\x3', '\x2', '\x2', '\x2', '-', '/', '\x3', '\x2', '\x2', '\x2', 
		'.', ',', '\x3', '\x2', '\x2', '\x2', '/', '\x30', '\a', '$', '\x2', '\x2', 
		'\x30', '\xE', '\x3', '\x2', '\x2', '\x2', '\x31', '\x32', '\t', '\a', 
		'\x2', '\x2', '\x32', '\x33', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', 
		'\b', '\b', '\x2', '\x2', '\x34', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'\a', '\x2', '\x1B', '#', '&', ',', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
