ArenaGrid(Arena(_tile(0,0,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,1,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,2,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,3,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,4,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,5,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,6,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,7,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,8,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,9,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,10,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,11,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,12,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,13,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,14,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,15,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,16,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,17,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,18,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(0,19,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,0,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,1,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,2,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,3,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,4,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,5,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,6,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,7,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,8,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,9,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,10,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,11,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,12,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,13,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,14,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,15,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,16,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,17,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,18,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(1,19,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,0,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,1,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,2,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,3,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,4,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,5,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,6,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,7,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,8,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,9,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,10,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,11,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,12,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,13,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,14,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,15,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,16,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(2,17,ArenaTile(empty(False))))).
ArenaGrid(Arena(_tile(2,18,ArenaTile(empty(False))))).
ArenaGrid(Arena(_tile(2,19,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,0,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,1,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,2,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,3,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,4,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,5,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,6,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,7,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,8,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,9,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,10,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,11,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,12,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,13,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,14,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,15,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,16,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(3,17,ArenaTile(empty(False))))).
ArenaGrid(Arena(_tile(3,18,ArenaTile(empty(False))))).
ArenaGrid(Arena(_tile(3,19,ArenaTile(empty(False))))).
ArenaGrid(Arena(_tile(4,0,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,1,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,2,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,3,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,4,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,5,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,6,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,7,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,8,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,9,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,10,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,11,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,12,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,13,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,14,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,15,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,16,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,17,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(4,18,ArenaTile(empty(False))))).
ArenaGrid(Arena(_tile(4,19,ArenaTile(empty(False))))).
ArenaGrid(Arena(_tile(5,0,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,1,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,2,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,3,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,4,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,5,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,6,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,7,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,8,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,9,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,10,ArenaTile(empty(False))))).
ArenaGrid(Arena(_tile(5,11,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,12,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,13,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,14,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,15,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,16,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,17,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(5,18,ArenaTile(empty(False))))).
ArenaGrid(Arena(_tile(5,19,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,0,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,1,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,2,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,3,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,4,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,5,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,6,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,7,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,8,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,9,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,10,ArenaTile(empty(False))))).
ArenaGrid(Arena(_tile(6,11,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,12,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,13,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,14,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,15,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,16,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,17,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,18,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(6,19,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,0,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,1,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,2,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,3,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,4,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,5,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,6,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,7,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,8,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,9,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,10,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,11,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,12,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,13,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,14,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,15,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,16,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,17,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,18,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(7,19,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,0,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,1,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,2,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,3,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,4,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,5,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,6,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,7,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,8,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,9,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,10,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,11,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,12,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,13,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,14,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,15,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,16,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,17,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,18,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(8,19,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,0,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,1,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,2,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,3,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,4,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,5,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,6,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,7,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,8,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,9,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,10,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,11,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,12,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,13,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,14,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,15,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,16,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,17,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,18,ArenaTile(empty(True))))).
ArenaGrid(Arena(_tile(9,19,ArenaTile(empty(True))))).
Spawner(Tetromino Spawner(TetrominoSpawner(nextTetrominoID(5)))).
Spawner(Tetromino Spawner(TetrominoSpawner(startPosition(position(x("-0,934800028800964")))))).
Spawner(Tetromino Spawner(TetrominoSpawner(startPosition(position(y("4,17000007629395")))))).
