setOnActuator(nextMove(pacman(playerController(nextStep(X))))):-
%blinky(blinky(positionToInt(x(X)))).
%blinky(blinky(positionToInt(y(X)))).
%clyde(clyde(positionToInt(x(X)))).
%clyde(clyde(positionToInt(y(X)))).
%inky(inky(positionToInt(x(X)))).
%inky(inky(positionToInt(y(X)))).
%pinky(pinky(positionToInt(x(X)))).
%pinky(pinky(positionToInt(y(X)))).
%pacman(pacman(positionToInt(x(X)))).
%pacman(pacman(positionToInt(y(X)))).
%extra(brain(aISupportScript(closestPelletX(X)))).
%extra(brain(aISupportScript(closestPelletY(X)))).
%extra(brain(aISupportScript(distanceClosestPellet(X)))).
%extra(brain(aISupportScript(powerup(X)))).
%extra(brain(aISupportScript(distances(X,distance(x1(V)))))).
%extra(brain(aISupportScript(distances(X,distance(y1(V)))))).
%extra(brain(aISupportScript(distances(X,distance(x2(V)))))).
%extra(brain(aISupportScript(distances(X,distance(y2(V)))))).
%extra(brain(aISupportScript(distances(X,distance(distance(V)))))).
%tiles(brain(aISupportScript(neededTiles(X,myTile(occupied(V)))))).
%tiles(brain(aISupportScript(neededTiles(X,myTile(pacdot(V)))))).
%tiles(brain(aISupportScript(neededTiles(X,myTile(x(V)))))).
%tiles(brain(aISupportScript(neededTiles(X,myTile(y(V)))))).
%previousMove(pacman(playerController(nextStep(X)))).
%prePreviousMove(pacman(playerController(prePreviousStep(X)))).
%availableDirections(pacman(playerController(avaialableMoves(X,myString(value(V)))))).
